# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 708ccf3c1d66bbdcaacfeb11ff45df6557a9e849dea6d10587025abedc9fd667b0d3111c66cc1c2dd94de078896f4f4eca83591bd19a23a58f9738ed43de1158

test:
  secret_key_base: 1581722e2e44c3123812c8c1013dc51c470e8d0758c0a4d35edf7c7adbc85dca41bd1a90591f435761d7e85ee6119db07a460d35be1c81289256d1061719e7c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
